### ISSUE TITLE
Customizable arguments to ctag/cscope commands

### ISSUE THREAD

**Issue by martinpelikan** [JCLiang/vim-cscope-utils#3]
Allowing additional arguments to the commands could benefit usage of other plugins. For example, [YouCompleteMe has support for ctags](https://github.com/Valloric/YouCompleteMe#the-gycm_collect_identifiers_from_tags_files-option) but requires the ```--fields=+l``` option to be used.

**Comment by JCLiang** [comment]
Fixed in e93dd0a11d7dae8ae85f72bd8eb9a743c268f58d.
