### ISSUE TITLE
Customizable and separate keybindings for cscope/ctags

### ISSUE THREAD

**Issue by martinpelikan** [JCLiang/vim-cscope-utils#4]
I find myself often wanting to update my ctags, but less often updating my cscope database. The latter takes on the order of tens of seconds, while the former is almost instant. It would be nice if the two were separate functions that could be mapped to whatever keys (to avoid conflicts with other mappings) the user would like to set. 

As an example:
```
nn <leader>ca :CScopeUtilsBuildAll<CR>
nn <leader>ct :CScopeUtilsBuildTags<CR>
nn <leader>pcs :CScopeUtilsBuildPycscope<CR>
nn <leader>cs :CScopeUtilsBuildCscope<CR>
```
and so on...

**Comment by JCLiang** [comment]
Fixed in 8519841ba81c43bc08d9be59aef3b10d22c51a74.
