### ISSUE TITLE
Silent mode for loading

### ISSUE THREAD

**Issue by martinpelikan** [JCLiang/vim-cscope-utils#5]
The [loading messages](https://github.com/JCLiang/vim-cscope-utils/blob/master/plugin/cscope_utils.vim#L107), while helpful at first, can get somewhat annoying when they require an extra key stroke to get rid of the dialog. Having a verbose/silent mode for loading could be nice for debugging and everyday use respectively.

**Comment by JCLiang** [comment]
Should be fixed with 3748d4cd29c97c0bbb8c90bbcf2774f12ab7a842. The messages are turned of by default now.
