### ISSUE TITLE
bindeval breaks Neovim and vim 7.3 compatibility 

### ISSUE THREAD

**Issue by martinpelikan** [JCLiang/vim-cscope-utils#8]
Since [Neovim does not support bindeval](https://github.com/neovim/neovim/issues/1898), 8519841ba81c43bc08d9be59aef3b10d22c51a74 breaks compatibility. I was able to work around this by simply doing ```:%s/bindeval/eval``` on the plugin code. Is there any downside to using eval over bindeval?

**Comment by JCLiang** [comment]
Oops, I'm no using neovim so I'm not aware of this. I noticed that bindeval() is smart enough to convert '1' (string) to 1 (integer), but in our case it doesn't really matter.

I've replaced bindeval() with eval() in d372be4a4c14e8978e006b0b9ffb8f5cbcc31ab8.
